name: Lacework 
description: Detects behaviors to find unknown threats through a patented form of behavioral analytics
author: https://github.com/erikwennerberg
requirements:
  - lacework
configuration:
  properties:
    scan-type:
        enum: [ "sca", "iac", "vulnerability","sast" ]
    iac-scan-type:
        enum: [ "cloudformation", "kubernetes", "helm","terraform","kustomize","secrets" ]
    vulnerability-scan-registry:
      type: string
    vulnerability-scan-repository:
      type: string
    vulnerability-scan-tag:
      type: string
    account-name:
      type: string
    api-key-env-var:
      type: string
    api-key-secret-env-var:
      type: string
    profile:
      type: string
  required:
    - account-name
    - scan-type
  additionalProperties: false